### PR TITLE
Handling logger initialisation error on windows.

### PR DESCRIPTION
**Pull request by hitman401**
**Fixes:**
Logger initialisation issue fixed. 
Unused packages removed from package.json
Ability to log from FFI worker process added.

Logging file names and line number not supported yet.

---

This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_launcher/146)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by shankar2105** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_launcher/146)*

**Comment by shankar2105** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_launcher/146)*

**Pull request merged**
