### PR TITLE
Add Service test

### PR DESCRIPTION
**Pull request by krishnaIndia**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/safe_launcher/39)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/launcher/parser/dns/add_service_v1_0.rs, line 74 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_launcher/39#-K1raxN66aUiOk1JFFVM)** ([raw file](https://github.com/maidsafe/safe_launcher/blob/6b195171d6abaf2380ff6284404b00bb68639988/src/launcher/parser/dns/add_service_v1_0.rs#L74)):</sup>
trailing space


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_launcher/39)

**Comment by ustulation** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[src/launcher/parser/dns/register_dns_v1_0.rs, line 43 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_launcher/39#-K1rbFDX4ZOQOMLI4VeW)** ([raw file](https://github.com/maidsafe/safe_launcher/blob/6b195171d6abaf2380ff6284404b00bb68639988/src/launcher/parser/dns/register_dns_v1_0.rs#L43)):</sup>
trailing space


---

<sup>**[src/launcher/parser/dns/register_dns_v1_0.rs, line 60 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_launcher/39#-K1rbIrCnxZZcbK0ulYO)** ([raw file](https://github.com/maidsafe/safe_launcher/blob/6b195171d6abaf2380ff6284404b00bb68639988/src/launcher/parser/dns/register_dns_v1_0.rs#L60)):</sup>
extra gap


---

<sup>**[src/launcher/parser/dns/register_dns_v1_0.rs, line 81 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_launcher/39#-K1rbLX5Njj05ycXXKrf)** ([raw file](https://github.com/maidsafe/safe_launcher/blob/6b195171d6abaf2380ff6284404b00bb68639988/src/launcher/parser/dns/register_dns_v1_0.rs#L81)):</sup>
extra gap


---

<sup>**[src/launcher/parser/dns/register_dns_v1_0.rs, line 84 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_launcher/39#-K1rbQgNp-hpcCafX8hw)** ([raw file](https://github.com/maidsafe/safe_launcher/blob/6b195171d6abaf2380ff6284404b00bb68639988/src/launcher/parser/dns/register_dns_v1_0.rs#L84)):</sup>
use random string


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_launcher/39)

**Comment by krishnaIndia** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[src/launcher/parser/dns/register_dns_v1_0.rs, line 43 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_launcher/39#-K1rbFDX4ZOQOMLI4VeW)** ([raw file](https://github.com/maidsafe/safe_launcher/blob/6b195171d6abaf2380ff6284404b00bb68639988/src/launcher/parser/dns/register_dns_v1_0.rs#L43)):</sup>
Done.


---

<sup>**[src/launcher/parser/dns/register_dns_v1_0.rs, line 81 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_launcher/39#-K1rbLX5Njj05ycXXKrf)** ([raw file](https://github.com/maidsafe/safe_launcher/blob/6b195171d6abaf2380ff6284404b00bb68639988/src/launcher/parser/dns/register_dns_v1_0.rs#L81)):</sup>
Done.


---

<sup>**[src/launcher/parser/dns/register_dns_v1_0.rs, line 84 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_launcher/39#-K1rbQgNp-hpcCafX8hw)** ([raw file](https://github.com/maidsafe/safe_launcher/blob/6b195171d6abaf2380ff6284404b00bb68639988/src/launcher/parser/dns/register_dns_v1_0.rs#L84)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_launcher/39)

**Comment by ustulation** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_launcher/39)

**Pull request merged**
