### PR TITLE
Network state handling

### PR DESCRIPTION
**Pull request by hitman401**
1. Network state handling implemented, which should move the user to re-login to connect to the network again
2. FFI process termination/load error handled. Closes the application after prompting the error to the user.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/safe_launcher/110)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by shankar2105** [comment]
Reviewed 10 of 13 files at r1, 2 of 2 files at r2.
Review status: 11 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_launcher/110)*

**Comment by shankar2105** [comment]
Reviewed 1 of 13 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_launcher/110)*

**Pull request merged**
